version: '2.1'
networks: {}
volumes:
  resin-data: {}
services:
  lowlevel:
    build:
      context: .
    privileged: true
    restart: always
    network_mode: host
    cap_add:
    - SYS_RAWIO
    volumes:
      - 'resin-data:/data'
    labels:
      io.balena.features.kernel-modules: '1'
      io.balena.features.firmware: '1'
      io.balena.features.dbus: '1'
      io.balena.features.supervisor-api: '1'
      io.balena.features.balena-api: '1'
